### ISSUE TITLE
Where is the dataset used for MSRBot?

### ISSUE THREAD

**Issue by QHZSS** [ahmad-abdellatif/MSRBot#1]
Hi, I'm looking for the dataset used in your work. You said in paper that the dataset is publicly available, but I couldn't find it.

**Comment by ahmad-abdellatif** [comment]
Hi,

Thanks for showing interest in our work.

Here is the link to the dataset: https://zenodo.org/record/33

**Comment by QHZSS** [comment]
Thanks but the link above says the record was removed.

**Comment by ahmad-abdellatif** [comment]
Sorry, I replaced a missing link. The following is the full link:
https://zenodo.org/record/3382071
